// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaalbnkucpnpphztnpcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYWxibmt1Y3BucHBoenRucGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njg0MTQsImV4cCI6MjA2OTA0NDQxNH0.0wR7G3W4wZYGPnFrXYyl6pHwjyZb_fjN0R2YrCWzGo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});